language: python
python:
- '2.7'
before_install:
- sudo apt-get -qq update
- sudo apt-get install gfortran libopenblas-dev liblapack-dev python-dev
install: 
- grep -v "^#" requirements.txt | xargs pip install
- python -m nltk.downloader punkt
script: python -m unittest discover
notifications:
  slack:
    secure: gC2OT+Nl54VCr43rWshKru5/IOlxSAWoD55egx06ZW7qTrp36AIfm5G0J2sSOqfJNWQem3NTDK3xN5k+kbBmE6WcKa9SqA7Xbpo6ZQtlio5fhiAgXhayC2ymW0rgFQRNc8WTR2eK7Kp6jtXvDKdEs44DH71iXmXOGWO2tj85tjA60eyLIk8LW6ucybgfhJknmmC6t9e1w1cLV4SFusbLcdjz/j/orlskUBHSihRF6Dg+zlkBuJieYGhCOmBWO/4QbH743uIOTKtDWHWbFjZglG4WKmuwa4mItQdvo7fVXS4jeXoCLsuHtT0Hq17Iv71490/urJhID/bmuxdZmztvJP+5bC6/C3oLp99QqFXMps8TBui7bQ63R2an6I6hRtOVRYQSMfSCA9reZzuB4ASHIeYpugIQJ2uLf8MedB6aTpLvWSVUxrlRMFlf06Igi27rcJ/wlTKzH7Jo7dqHuuBrFl3eW4fJd8C4h/CON3jVxENhob1EiZzlbPNNICVwohHUeDr191HQmocOhwgSabGT17oJ6PVaxeunEfBSTY5E3ABSMImn6xn0RR/Udzge1qhy03hEAmINsDaYSuITNjyWYD96KrX8SRqBPDg8vhHFccq7G7YbqqPhK6+7O8ZLjip7elcBITrEZ3wvA37c/C366mfza3EFtSR2PJKeJwUfA0A=
